spring:
  application:
    name: weather-collection-eureka-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  client:
    config:
      remote-service:
        connectTimeout: 5000
        readTimeout: 5000